# CodeMagic CI/CD configuration for Pharmacy Management System Android App
# Documentation: https://docs.codemagic.io/getting-started/building-for-android/

workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      # Uncomment and configure after setting up keystore in CodeMagic UI:
      # Go to Settings > Android > Keystore to upload your keystore file
      # android_signing:
      #   - keystore_reference
      # groups:
      #   - keystore_credentials
      vars:
        PACKAGE_NAME: "com.pharmacy.pms"
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$HOME/Library/Android/sdk" > $CM_BUILD_DIR/local.properties
      - name: Make gradlew executable
        script: |
          cd $CM_BUILD_DIR
          chmod +x gradlew
      - name: Build release APK
        script: |
          cd $CM_BUILD_DIR
          ./gradlew clean assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false
      scripts:
        - name: "Example: Upload to Firebase App Distribution"
          script: |
            # Uncomment and configure if using Firebase App Distribution
            # firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk \
            #   --app YOUR_APP_ID \
            #   --groups "testers" \
            #   --release-notes "Release build from CodeMagic - $(date +'%Y-%m-%d %H:%M:%S')"
  
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.pharmacy.pms"
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$HOME/Library/Android/sdk" > $CM_BUILD_DIR/local.properties
      - name: Make gradlew executable
        script: |
          cd $CM_BUILD_DIR
          chmod +x gradlew
      - name: Build debug APK
        script: |
          cd $CM_BUILD_DIR
          ./gradlew clean assembleDebug
      - name: Run tests
        script: |
          cd $CM_BUILD_DIR
          ./gradlew test
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/test-results/**/*
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true

  android-qa:
    name: Android QA Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.pharmacy.pms"
        BUILD_TYPE: "qa"
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$HOME/Library/Android/sdk" > $CM_BUILD_DIR/local.properties
      - name: Make gradlew executable
        script: |
          cd $CM_BUILD_DIR
          chmod +x gradlew
      - name: Build QA APK
        script: |
          cd $CM_BUILD_DIR
          ./gradlew clean assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - qa-team@example.com
        notify:
          success: true
          failure: true
